services:
  neo4j:
    image: neo4j:5.20
    container_name: neo4j-ollama
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./init.cypher:/init.cypher